version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: America/Mexico_City
    open-pull-requests-limit: 5
    commit-message:
      prefix: chore
      include: scope
    labels:
      - dependencies
    groups:
      types:
        patterns:
          - "@types/*"
      eslint:
        patterns:
          - eslint
          - "@typescript-eslint/*"
      testing:
        patterns:
          - sinon
          - mocha
          - "@types/sinon"
          - "@types/mocha"
          - superagent-mock
      prod-deps:
        dependency-type: production
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "eslint"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "chalk"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "prettier"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "yargs"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "rimraf"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "superagent"
        update-types: [ "version-update:semver-major" ]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: chore
      include: scope
    labels:
      - dependencies
      - ci
